language: python

matrix:
    include:
        # PEP 8 checks
        - os: linux
          python: 2.7
          env:
            - TOXENV=flake8
       
        # Run as a regular user
        - os: linux
          python: 2.7
          env:
            - TOXENV=py27-linux_non_root,codecov

        - os: linux
          python: 3.4
          env:
            - TOXENV=py34-linux_non_root,codecov

        - os: linux
          python: 3.5
          env:
            - TOXENV=py35-linux_non_root,codecov

        - os: linux
          python: 3.6
          env:
            - TOXENV=py36-linux_non_root,codecov

        - os: linux
          python: pypy
          env:
            - SCAPY_COVERAGE=yes

        - os: linux
          python: pypy3
          env:
            - SCAPY_COVERAGE=yes

        - os: osx
          language: generic
          env:
            - SCAPY_COVERAGE=yes

        - os: osx
          language: generic
          env:
            - SCAPY_USE_PCAPDNET=yes SCAPY_COVERAGE=yes

        # Run as root
        - os: linux
          sudo: required
          python: 2.7
          env:
            - TOXENV=py27-linux_root,codecov

        - os: linux
          sudo: required
          python: 3.4
          env:
            - TOXENV=py34-linux_root,codecov

        - os: linux
          sudo: required
          python: 3.5
          env:
            - TOXENV=py35-linux_root,codecov

        - os: linux
          sudo: required
          python: 3.6
          env:
            - TOXENV=py36-linux_root,codecov

        - os: linux
          sudo: required
          python: 2.7
          virtualenv:
            system_site_packages: true
          env:
            - SCAPY_SUDO=sudo SCAPY_USE_PCAPDNET=yes SCAPY_COVERAGE=yes

        - os: osx
          language: generic
          env:
            - SCAPY_SUDO=sudo SCAPY_COVERAGE=yes

        - os: osx
          language: generic
          env:
            - SCAPY_SUDO=sudo SCAPY_USE_PCAPDNET=yes SCAPY_COVERAGE=yes

        - os: osx
          language: generic
          env:
            - TOXENV=py36-osx_non_root,py36-osx_root,codecov

install: bash .travis/install.sh

script: bash .travis/test.sh
